# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    paths:
       - *.cs
       - *.xaml
       - *.csproj
       - *.sln
  pull_request:
    branches: [ "master" ]
    paths:
       - *.cs
       - *.xaml
       - *.csproj
       - *.sln

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: |
        dotnet workload install maui
        dotnet workload restore
        dotnet restore
    - name: Run
      run: |
        dotnet build -t:Run -f net7.0-android -p:Configuration=Debug
