name: Build

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        version: 7.0.x

    - name: Install
      run: |
        dotnet workload restore
        dotnet restore
    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_KEY }}
        P12_PASSWORD: ${{ secrets.PWD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPLE_CER }}
        KEYCHAIN_PASSWORD: ${{ secrets.PWD }}
      run: |
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

    - name: Build
      run: |
        dotnet publish -f:net7.0-ios -c:Release -p:RuntimeIdentifier=ios-arm64

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: bin/Release/net7.0-ios/ios-arm64/publish/*.ipa